### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by keysh** [justdeleteme/justdelete.me#731] opened 2017-02-22 20:08 UTC
I see 130 pull requests, 17 open issues and last commit was months ago. Has this project any bright future or is it definitively dead?

**Comment by chamini2** [comment] 2017-03-03 01:26
How about adding some Collaborators people interested in it. Looking at the [contributors page](https://github.com/justdeleteme/justdelete.me/graphs/contributors) might be a good start.

**Comment by burriep** [comment] 2017-03-12 01:47
Yes, it would be great if the project owners would allow someone else who is interested to maintain the project right from this repo. The information would be very useful if it was up-to-date but it isn't anymore for many sites.
Otherwise one of the forks of this repo could take over since the maintainers don't seem to care to keep this project up to date. I'd consider helping update it. It seems static enough that the site could be hosted on GitHub Pages for ease of maintenance.

**Comment by ldexterldesign** [comment] 2017-03-24 14:14
https://twitter.com/ldexterldesign/status/845276974281113605

Hey all,

Frankly, disappointed to see the state of JDM since last time I checked

What's http://backgroundchecks.org/ influence/involvement here?

Hope to hear back

Cheers

**Comment by tupaschoal** [comment] 2017-03-24 23:42
Hey @keysh, @chamini2, @burriep and @ldexterldesign,

I configured [my fork](https://github.com/tupaschoal/justdelete.me) with github pages, removed all the shady background checks and broken links and added a continuous integration tool (TravisCI). We could resume from there, if you'd like. I'll definitely need help spreading the word on all the PR.

**Comment by burriep** [comment] 2017-03-24 23:56
Hey @tupaschoal,
Thanks for getting your fork setup. That sounds like the best option at the moment.

**Comment by liberland-liberland** [comment] 2017-04-10 01:54
@tupaschoal enable "issues" and I will repost my issue there

**Comment by tupaschoal** [comment] 2017-04-10 02:02
Done @liberland-liberland

**Comment by PyroSamurai** [comment] 2017-04-10 03:56
@rmlewisuk now would be a good time to start completing those PRs like you said you should on twitter.

**Comment by neeklamy** [comment] 2017-04-10 15:18
Sadly it looks like this project is no more. It changed hands some time in September or October 2016 (note the 3 commits in October 2016 by the new owner, ‘justdeleteme’).

I contacted Robb to ask him about this issue, he confirmed that he no longer has control over it and that the new owner isn’t doing much with it.

Then there’s this:

> JustDeleteMe seems to be dead regarding the GitHub repro. I want to help by merge pull request and by updating it.
> – David Maciejewski

> It's under new ownership and no longer controlled by us.
> – Robb Lewis

> I know. But I could not find anyone who is responsible for this. Could you help out to connect?
> – David Maciejewski

[no reply]
Source: [Twitter conversation, 5 February 2017](https://twitter.com/macx/status/828274771267878913)

**Comment by PyroSamurai** [comment] 2017-04-11 00:09
@neeklamy Something smells fishy.
I've used some of my internet tracking skills to lift some information about the new owners of the repo.

What I've found out so far:

1. the github user justdeleteme uses the email backgroundchecks(at)wiredrhino(dot).com to commit
2. wiredrhino(dot)com is owned by Wired Rhino, Inc which is owned by Ariel Ozick
3. Wired Rhino Inc's address: 113 Barksdale Pro Ctr Newark, Delaware 19711  
4. Wired Rhino Inc's phone number: (646) 736 7492
I found the above info [here](https://www.chamberofcommerce.com/newark-de/8250047-ariel-ozick) which has Ariel Ozick's name in the link so I'm pretty sure it is correct.

So, anyways, you can contact that person if you like but I'm pretty sure Robb sold JDM which is why he won't give us any straight answers, so the project can't go back to him. I pretty sure most here would prefer a better distribution of commit power in a new repo so I've implemented a solution. I've sent an invite to the two contributors in this conversation.

**Comment by tupaschoal** [comment] 2017-04-11 01:32
@PyroSamurai, I have my fork pretty much set up. Removed all the fishy information and installed some CI tools, if you agree we can take from there.

**Comment by PyroSamurai** [comment] 2017-04-11 01:34
@tupaschoal that's exactly what I was thinking. Transfer it over to the org, all members have admin rights so you can commit and create as you wish.

**Comment by tupaschoal** [comment] 2017-04-11 01:48
Done.

**Comment by PyroSamurai** [comment] 2017-04-11 01:54
@tupaschoal Great, no we just have to gather everyone over there. Which honestly might take a couple months but we can start trying reintegrating the repos and pull requests as soon as we have a couple people. As for who to invite outside of this thread, I leave it to you and neeklamy since I don't know who to trust yet. Remember, anybody who joins at the moment will have admin rights, so exercise your invite powers cautiously.

**Comment by PyroSamurai** [comment] 2017-04-11 01:56
new repo is [here](https://github.com/jdm-contrib) everyone.

**Comment by tupaschoal** [comment] 2017-04-11 01:57
@PyroSamurai I thought about slowly inviting people to reopen their pull requests/issues on the other repo and closing them here. If we can get them to do so, we can clear up the most recent issues and PRs here so that this issue stays on top.

In any case, I don't mind it taking a couple of months, as long as we have it healthy and working :)

**Comment by PyroSamurai** [comment] 2017-04-11 02:04
@tupaschoal Sounds good to me, by the way you and @neeklamy (when they join) should make your membership public. I'm just facilitator so my membership stay private (I'm not important to the project). Start an issue in new repo so we can continue this conversation there. I'll drop a link to it here once it is made.

**Comment by tupaschoal** [comment] 2017-04-11 02:10
Done both.

**Comment by PyroSamurai** [comment] 2017-04-11 02:11
Nice

**Comment by neeklamy** [comment] 2017-04-12 08:27
Thanks for the investigation, @PyroSamurai, I suspected the JDM project and the related Google Chrome extension changed hands with the intention of injecting adware ([OMG! Chrome! – Adware Companies Are Buying Up Popular Chrome Add-Ons](http://www.omgchrome.com/malware-buying-google-chrome-extensions/)).

Looks like that was about right, “Wired Rhino specializes in Web Publishing, Domain Acquisition, Lead Generation and Performance Marketing.” – [LinkedIn](https://www.linkedin.com/company/wired-rhino-inc.)

**Closed** 2017-07-18 15:31 UTC
